name: Daily Screenshot

on:
  schedule:
    # Run the job every day at noon (12:00 PM UTC)
    - cron: '0 12 * * *'

jobs:
  take-screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pillow

    - name: Download ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/110.0.5481.77/chromedriver_linux64.zip
        unzip /tmp/chromedriver.zip -d /usr/local/bin/

    - name: Install Chrome browser
      run: |
        sudo apt-get install -y chromium-browser

    - name: Run screenshot script
      run: python capture_screenshot.py

    - name: Upload screenshot
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: screenshot_*.png